# Generated by Django 5.2.8 on 2025-11-24 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_item', models.CharField(max_length=200, verbose_name='Nama Menu')),
                ('deskripsi_item', models.TextField(blank=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga')),
                ('status_ketersediaan', models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('HABIS', 'Habis')], default='TERSEDIA', max_length=10)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.kategori')),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(default='Anonim', max_length=100)),
                ('rating', models.IntegerField(help_text='Rating dari 1 sampai 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('komentar', models.TextField(blank=True)),
                ('tanggal_review', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menu')),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
    ]
